coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
        if_not_found: success
    patch:
      default:
        target: 80%
        if_not_found: success

flags:
  spark-core:
    paths:
      - packages/spark-core/
    carryforward: true
  spark-node:
    paths:
      - packages/spark-node/
    carryforward: true

comment:
  layout: "reach,diff,flags,components"
  behavior: default
  require_changes: false

ignore:
  - "packages/spark-connect/**"
  - "examples/**"
  - "tooling/**"
  - "**/*.test.js"
