import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { Column, col, lit } from "../column.js";
import { InvalidInputError } from "../errors.js";
import {
  when,
  cast,
  coalesce,
  isnull,
  isnan,
  isnotnull,
  nanvl,
  ifnull,
  nvl,
  nvl2,
  nullif,
  expr,
  monotonically_increasing_id,
  spark_partition_id,
  typeof_,
  uuid,
  broadcast,
} from "./conditional.js";

function assertFn(c: Column, name: string, argCount?: number) {
  assert.equal(c._expr.type, "unresolvedFunction");
  if (c._expr.type === "unresolvedFunction") {
    assert.equal(c._expr.name, name);
    if (argCount !== undefined) assert.equal(c._expr.arguments.length, argCount);
  }
}

describe("when/otherwise", () => {
  it("builds a when expression with otherwise", () => {
    const result = when(col("age").gt(lit(18)), lit("adult")).otherwise(lit("child"));
    assert.equal(result._expr.type, "caseWhen");
    if (result._expr.type === "caseWhen") {
      assert.equal(result._expr.branches.length, 1);
      assert.deepStrictEqual(result._expr.elseValue, lit("child")._expr);
    }
  });

  it("chains multiple when clauses", () => {
    const result = when(col("age").gt(lit(18)), lit("adult"))
      .when(col("age").gt(lit(12)), lit("teen"))
      .otherwise(lit("child"));
    if (result._expr.type === "caseWhen") {
      assert.equal(result._expr.branches.length, 2);
      assert.notEqual(result._expr.elseValue, undefined);
    }
  });

  it("builds when without otherwise via toColumn", () => {
    const result = when(col("age").gt(lit(18)), lit("adult")).toColumn();
    if (result._expr.type === "caseWhen") {
      assert.equal(result._expr.branches.length, 1);
      assert.equal(result._expr.elseValue, undefined);
    }
  });

  it("is a Column, usable without toColumn()", () => {
    const chain = when(col("age").gt(lit(18)), lit("adult"));
    assert.ok(chain instanceof Column);
    assert.deepStrictEqual(chain.alias("label")._expr, {
      type: "alias",
      inner: chain._expr,
      name: "label",
    });
  });

  it("auto-wraps primitive values", () => {
    const result = when(col("age").gt(18), "adult").otherwise("child");
    if (result._expr.type === "caseWhen") {
      assert.deepStrictEqual(result._expr.branches[0].value, lit("adult")._expr);
      assert.deepStrictEqual(result._expr.elseValue, lit("child")._expr);
    }
  });

  it("rejects when()/otherwise() on a column that is not an open chain", () => {
    assert.throws(
      () => col("age").when(col("x").gt(1), lit("y")),
      (err: unknown) =>
        err instanceof InvalidInputError &&
        /previously generated by the when\(\)/.test(err.message),
    );
    assert.throws(() => col("age").otherwise(lit("y")), InvalidInputError);
  });

  it("rejects extending a chain already closed by otherwise()", () => {
    const closed = when(col("age").gt(18), "adult").otherwise("child");
    assert.throws(
      () => closed.when(col("age").gt(12), lit("teen")),
      (err: unknown) => err instanceof InvalidInputError && /once otherwise\(\)/.test(err.message),
    );
    assert.throws(() => closed.otherwise(lit("other")), InvalidInputError);
  });
});

describe("cast()", () => {
  it("creates a cast expression from a Column", () => {
    const result = cast(col("id"), "string");
    assert.equal(result._expr.type, "cast");
    if (result._expr.type === "cast") {
      assert.equal(result._expr.targetType, "string");
    }
  });

  it("creates a cast expression from a string column name", () => {
    const result = cast("price", "double");
    assert.equal(result._expr.type, "cast");
  });

  it("Column.cast() method works", () => {
    const result = col("id").cast("string");
    assert.equal(result._expr.type, "cast");
    if (result._expr.type === "cast") {
      assert.equal(result._expr.targetType, "string");
    }
  });
});

describe("null/predicate functions", () => {
  it("coalesce handles multiple columns", () => {
    const result = coalesce("a", "b", "c");
    if (result._expr.type === "unresolvedFunction") {
      assert.equal(result._expr.arguments.length, 3);
    }
  });

  it("isnull/isnan/isnotnull", () => {
    assertFn(isnull("x"), "isnull", 1);
    assertFn(isnan("x"), "isnan", 1);
    assertFn(isnotnull("x"), "isnotnull", 1);
  });

  it("nanvl takes two columns", () => {
    assertFn(nanvl("x", "y"), "nanvl", 2);
  });

  it("ifnull/nvl are aliases", () => {
    assertFn(ifnull("x", "y"), "ifnull", 2);
    assertFn(nvl("x", "y"), "ifnull", 2);
  });

  it("nvl2 takes three args", () => {
    assertFn(nvl2("x", "y", "z"), "nvl2", 3);
  });

  it("nullif takes two args", () => {
    assertFn(nullif("x", "y"), "nullif", 2);
  });
});

describe("utility functions", () => {
  it("expr() creates expressionString", () => {
    const result = expr("id + 1");
    assert.equal(result._expr.type, "expressionString");
    if (result._expr.type === "expressionString") {
      assert.equal(result._expr.expression, "id + 1");
    }
  });

  it("monotonically_increasing_id() is zero-arg", () => {
    assertFn(monotonically_increasing_id(), "monotonically_increasing_id", 0);
  });

  it("spark_partition_id() is zero-arg", () => {
    assertFn(spark_partition_id(), "spark_partition_id", 0);
  });

  it("typeof_ creates unresolvedFunction", () => {
    assertFn(typeof_("x"), "typeof", 1);
  });

  it("uuid() is zero-arg", () => {
    assertFn(uuid(), "uuid", 0);
  });

  it("broadcast passes through column", () => {
    const result = broadcast(col("x"));
    // broadcast is a pass-through, not an unresolvedFunction
    assert.equal(result._expr.type, "unresolvedAttribute");
  });
});
